
spring:
  application:
    name: person-client
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#ribbon:
#  eureka:
#    enabled: false
    ##Ribbon不适用Eureka

#person-service:
#  ribbon:
#    listOfServers: http://localhost:9090,http://localhost:9090,http://localhost:9090
